# Numpy

In [1]:
import numpy as np

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [6]:
np.array(benimListem) #numpy dizisi olusturduk.

array([20, 30, 40])

In [7]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [8]:
matrixListesi[1]

[20, 30, 40]

In [9]:
matrixListesi[1][2]

40

In [10]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [11]:
matrixListesi

[[10, 20, 30], [20, 30, 40], [30, 40, 50]]

## arange

In [12]:
range(0,10)

range(0, 10)

In [14]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(0,10) #bir numpy dizisi olusturuyoruz.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2) #buradaki 2, atlayarak gitmesine olanak saglar. 2,2 gider.

array([0, 2, 4, 6, 8])

## zeros

In [17]:
np.zeros(5) #icinde 5 tane sifir olan dizi olusturur.

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,2)) #matrix olarak dizi icerisinde dizi formatini yapariz.

array([[0., 0.],
       [0., 0.]])

## ones

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [21]:
np.linspace(0,20,5) #esit dagitilmis 5 farkli sayi getir.

array([ 0.,  5., 10., 15., 20.])

In [22]:
np.linspace(0,20,6) #esit dagitilmis 6 farkli sayi getir.

array([ 0.,  4.,  8., 12., 16., 20.])

In [23]:
np.linspace(0,10,20) #esit dagitilmis 0 ve 10 arasi 20 sayi getir.

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [25]:
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

## eye

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(10) #buradaki 1'lere iyi bak.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [34]:
np.random.randn(4)

array([-0.26624352,  0.06358572,  0.38583529, -0.2188302 ])

In [36]:
np.random.randn(3,3)

array([[ 0.60485286, -0.17986562,  2.11199129],
       [-0.40415474,  0.09645081,  0.25467218],
       [ 1.73276182, -0.68383621,  0.27278062]])

In [40]:
np.random.randint(1,10)

7

In [41]:
np.random.randint(1,10,4)

array([5, 9, 9, 3])

In [42]:
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
RandomDizim = np.random.randint(0,40,20)

In [44]:
RandomDizim

array([35,  0, 14, 38, 32, 22, 14, 22, 16, 25,  5,  4, 33, 22, 37, 27,  7,
       10, 29, 30])

## numpy array methods

In [47]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [48]:
RandomDizim.reshape(4,5)

array([[35,  0, 14, 38, 32],
       [22, 14, 22, 16, 25],
       [ 5,  4, 33, 22, 37],
       [27,  7, 10, 29, 30]])

In [49]:
 benimNumpyDizim.max()

29

In [50]:
RandomDizim.max()

38

In [51]:
benimNumpyDizim.min()

0

In [52]:
RandomDizim.min()

0

In [53]:
RandomDizim.argmax() #en yuksek degerin indexini soyler.

3

In [54]:
RandomDizim.argmin() #minimum degerin indexini ifade eder.

1

In [55]:
benimNumpyDizim.shape

(30,)

In [57]:
reshapedizi = benimNumpyDizim.reshape(5,6)

In [58]:
reshapedizi.shape

(5, 6)

In [59]:
bDizi = np.arange(0,15)

In [60]:
bDizi[3:8] = -5 #index 3'den 8'e kadar olanlara -5 atadik.
bDizi

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [61]:
baskaDizi = np.arange(0,24)

In [62]:
slicingDizi = baskaDizi[4:9]

In [63]:
slicingDizi[:] = 700

In [64]:
slicingDizi

array([700, 700, 700, 700, 700])

In [65]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [66]:
ornekDizi = np.arange(0,24)
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
ornekDiziKopyasi = ornekDizi.copy()

In [68]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [70]:
ornekDiziKopyaSlicing[:] = 800

In [71]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [72]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [73]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [74]:
myList = [[10,20,30],[20,30,40],[40,50,60]]

In [75]:
myMd = np.array(myList)

In [76]:
myMd

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [77]:
myMd[0]

array([10, 20, 30])

In [78]:
myMd[1][2]

40

In [79]:
myMd[1,2]

40

In [80]:
myMd[1:,2]

array([40, 60])

In [81]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [82]:
newMatrix = np.array(newList)

In [84]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
newMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operations

In [87]:
doubleNewList = np.random.randint(1,100,20)
doubleNewList

array([69, 87, 48, 46,  2, 56, 11, 67, 81, 91, 51, 66, 76, 24, 67, 88, 36,
       11, 77, 47])

In [88]:
doubleNewList > 24

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True])

In [89]:
doubleNewList

array([69, 87, 48, 46,  2, 56, 11, 67, 81, 91, 51, 66, 76, 24, 67, 88, 36,
       11, 77, 47])

In [90]:
sonucDizisi = doubleNewList > 24
sonucDizisi

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True])

In [91]:
doubleNewList[sonucDizisi]

array([69, 87, 48, 46, 56, 67, 81, 91, 51, 66, 76, 67, 88, 36, 77, 47])

In [92]:
doubleNewList

array([69, 87, 48, 46,  2, 56, 11, 67, 81, 91, 51, 66, 76, 24, 67, 88, 36,
       11, 77, 47])

In [93]:
doubleNewList[doubleNewList > 24]

array([69, 87, 48, 46, 56, 67, 81, 91, 51, 66, 76, 67, 88, 36, 77, 47])

In [94]:
lastArray = np.arange(0,24)
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [95]:
lastArray + lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [96]:
lastArray*lastArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [97]:
lastArray-lastArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [98]:
np.sqrt(lastArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [99]:
np.max(lastArray)

23

In [100]:
np.min(lastArray)

0